# Site settings
title: Massil Achab
# email: your-email@domain.com
description: >
  A blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://massil94.github.io" # the base hostname & protocol for your site
twitter_username: loodazy
github_username:  massil94

# Build settings
markdown: kramdown

# Output settings
permalink: none
